version: "3"

services:
  nginx.latest:
    container_name: http-server
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./.docker-config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - "80:80"
    networks:
      - necodeo

  php.83:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - "9000:9000"
    networks:
      - necodeo

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    networks:
      - necodeo

  minio.latest:
    container_name: s3-server
    build:
      context: .
      dockerfile: Dockerfile.minio
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    ports:
      - "9030:9000"
      - "9031:9031"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - necodeo

networks:
  necodeo:

# extra_hosts:
#   - "host.docker.internal:host-gateway"

volumes:
  minio:
  vendor:
