version: "3"

services:
  minio:
    build: .
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    ports:
      - "9030:9000"
      - "9031:9031"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  minio:
