<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230721143009 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE nc_account_authkeys (id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, account_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, type VARCHAR(256) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, `key` VARCHAR(1024) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_account_profiles (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, account_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, display_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, bio VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, birthdate DATE DEFAULT NULL, image_id_avatar CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, image_id_background CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, link_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_account_sessions (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, account_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, `key` VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, ua VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, ip VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME DEFAULT NULL, accessed_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_account_verifications (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, account_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, code VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME NOT NULL, verified_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_categories (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, lp INT DEFAULT NULL, rp INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, resource_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_categories_product_attributes (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, category_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, product_attribute_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_complaints (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, order_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, product_id INT DEFAULT NULL, reason VARCHAR(2048) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME DEFAULT NULL, account_id_creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_contents (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, cached_fragments TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, account_id_editor CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, account_id_publisher CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, published_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_contents_fragments (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, content_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, fragment_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, `order` INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_contents_products (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, content_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, product_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_coupons (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME DEFAULT NULL, account_id_creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, discount_type CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_delivery_points (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_discount_types (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, value DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_forum_categories (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, lp INT DEFAULT NULL, rp INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, resource_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_forum_threads (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, lp INT DEFAULT NULL, rp INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_fragments (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, type VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, data TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, account_id_author CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_image_thumbnails (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, image_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, local_path VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, remote_path VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, resolution_x INT NOT NULL, resolution_y INT NOT NULL, size BIGINT NOT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_images (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, type VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, local_path VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, remote_path VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, resolution_x INT DEFAULT NULL, resolution_y INT DEFAULT NULL, size BIGINT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_links (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, http_req_method VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, http_req_uri VARCHAR(2048) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, http_res_status_code INT NOT NULL, content_type VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, content_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_nav_groups (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_nav_items (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, nav_group_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, parent_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, link_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, `order` INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_order_invoices (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, order_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, local_path VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, remote_path VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME DEFAULT NULL, generated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_order_payments (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, order_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, payment_provider_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, value DOUBLE PRECISION DEFAULT NULL, status VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME DEFAULT NULL, paid_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_order_shipments (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, order_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, shipping_provider_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, status VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME DEFAULT NULL, shipped_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_orders (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, account_id_customer VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, calculated_price NUMERIC(10, 2) DEFAULT NULL, ordered_at DATETIME DEFAULT NULL, payment_created_at DATETIME DEFAULT NULL, payment_paid_at DATETIME DEFAULT NULL, shipment_created_at DATETIME DEFAULT NULL, shipment_shipped_at DATETIME DEFAULT NULL, invoice_created_at DATETIME DEFAULT NULL, invoice_generated_at DATETIME DEFAULT NULL, status VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_orders_products (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, order_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, product_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, quantity INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_payment_providers (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_product_attributes (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_product_reviews (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, product_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, account_id_reviewer CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, rating TINYINT(1) DEFAULT NULL, comment VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_products (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, price NUMERIC(10, 2) DEFAULT NULL, quantity INT DEFAULT NULL, dimension_x DOUBLE PRECISION DEFAULT NULL, dimension_y DOUBLE PRECISION DEFAULT NULL, dimension_z DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, gtin VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, brand VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_products_categories (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, product_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, category_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_products_product_categories (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, product_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, product_attribute_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_resources (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_returns (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, order_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, product_id INT DEFAULT NULL, reason VARCHAR(2048) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_roles (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_setting_groups (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_setting_items (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, nav_group_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, parent_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, value VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, `order` INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_shipping_providers (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nc_accounts (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, phone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_polish_ci`, created_at DATETIME NOT NULL, is_verified TINYINT(1) NOT NULL, authkey_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'DEFAULT\' COLLATE `utf8mb4_polish_ci`, role_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_polish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_polish_ci` ENGINE = InnoDB');
    
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE nc_account_authkeys');
        $this->addSql('DROP TABLE nc_account_profiles');
        $this->addSql('DROP TABLE nc_account_sessions');
        $this->addSql('DROP TABLE nc_account_verifications');
        $this->addSql('DROP TABLE nc_categories');
        $this->addSql('DROP TABLE nc_categories_product_attributes');
        $this->addSql('DROP TABLE nc_complaints');
        $this->addSql('DROP TABLE nc_contents');
        $this->addSql('DROP TABLE nc_contents_fragments');
        $this->addSql('DROP TABLE nc_contents_products');
        $this->addSql('DROP TABLE nc_coupons');
        $this->addSql('DROP TABLE nc_delivery_points');
        $this->addSql('DROP TABLE nc_discount_types');
        $this->addSql('DROP TABLE nc_forum_categories');
        $this->addSql('DROP TABLE nc_forum_threads');
        $this->addSql('DROP TABLE nc_fragments');
        $this->addSql('DROP TABLE nc_image_thumbnails');
        $this->addSql('DROP TABLE nc_images');
        $this->addSql('DROP TABLE nc_links');
        $this->addSql('DROP TABLE nc_nav_groups');
        $this->addSql('DROP TABLE nc_nav_items');
        $this->addSql('DROP TABLE nc_order_invoices');
        $this->addSql('DROP TABLE nc_order_payments');
        $this->addSql('DROP TABLE nc_order_shipments');
        $this->addSql('DROP TABLE nc_orders');
        $this->addSql('DROP TABLE nc_orders_products');
        $this->addSql('DROP TABLE nc_payment_providers');
        $this->addSql('DROP TABLE nc_product_attributes');
        $this->addSql('DROP TABLE nc_product_reviews');
        $this->addSql('DROP TABLE nc_products');
        $this->addSql('DROP TABLE nc_products_categories');
        $this->addSql('DROP TABLE nc_products_product_categories');
        $this->addSql('DROP TABLE nc_resources');
        $this->addSql('DROP TABLE nc_returns');
        $this->addSql('DROP TABLE nc_roles');
        $this->addSql('DROP TABLE nc_setting_groups');
        $this->addSql('DROP TABLE nc_setting_items');
        $this->addSql('DROP TABLE nc_shipping_providers');
        $this->addSql('DROP TABLE nc_accounts');
    }
}
