controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
paper-docs:
    path: /docs
    host: "{paper-api.necodeo.com|paper-api.localhost}"
    methods: GET
    defaults: { _controller: 'App\Controller\Paper\SwaggerUiController' }
admin-docs:
    path: /docs
    host: "{admin-api.necodeo.com|admin-api.localhost}"
    methods: GET
    defaults: { _controller: 'App\Controller\Admin\SwaggerUiController' }
